name: Code Checks
description: Checks code for compliance using linting, tests, etc.

runs:
  using: 'composite'
  steps:
    - name: Stylelint
      run: pnpm run stylelint
      shell: bash

    - name: Prettier Check
      run: pnpm run prettier-check
      shell: bash
