name: On PR To Main Branch

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  checks:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Prep Project
        uses: ./.github/composite-actions/node-setup-ubuntu

      - name: Code Checks
        uses: ./.github/composite-actions/code-checks
